language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    include:
        - php: 7.2
        - php: 7.2
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    fast_finish: true

before_install: composer self-update

install: composer update $COMPOSER_FLAGS --prefer-source -n

script: bin/phpunit --verbose
