language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    include:
        - php: 5.6
        - php: 5.6
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
        - php: 7
        - php: 7
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
        - php: nightly
        - php: hhvm
    allow_failures:
        - php: nightly
        - php: hhvm
    fast_finish: true

before_install: composer self-update

install: composer update $COMPOSER_FLAGS --prefer-source -n

script: bin/phpunit --verbose
